/* PHYSIQUE OS service worker — generated by build.mjs. Version 1.0.0+c8996540df */
var VERSION='physique-os-1.0.0-89c84fd18981'; /* release identity, not source identity: a change to the build pipeline or reference data must also invalidate the cache */
var SHELL=['./','./index.html','./manifest.webmanifest','./icons/icon.svg','./icons/favicon.svg','./icons/favicon-32.png','./icons/favicon-16.png','./icons/icon-192.png','./icons/icon-512.png','./icons/maskable-512.png','./icons/apple-touch-icon.png','./data/reference/compendium-2024.json'];
self.addEventListener('install',function(e){e.waitUntil(caches.open(VERSION).then(function(c){return Promise.all(SHELL.map(function(u){return c.add(u).catch(function(){});}));}));});
self.addEventListener('activate',function(e){e.waitUntil(caches.keys().then(function(keys){return Promise.all(keys.filter(function(k){return k!==VERSION&&k.indexOf('physique-os-')===0;}).map(function(k){return caches.delete(k);}));}).then(function(){return self.clients.claim();}));});
self.addEventListener('message',function(e){if(e.data&&e.data.type==='SKIP_WAITING')self.skipWaiting();});
self.addEventListener('fetch',function(e){
  var req=e.request;if(req.method!=='GET')return;var url=new URL(req.url);if(url.origin!==location.origin)return;
  var isData=url.pathname.indexOf('/data/')>=0;var isHTML=req.mode==='navigate'||/\/$|index\.html$/.test(url.pathname);
  if(isData){e.respondWith(caches.open(VERSION).then(function(c){return c.match(req).then(function(hit){if(hit)return hit;return fetch(req).then(function(res){if(res&&res.ok)c.put(req,res.clone());return res;});});}));return;}
  if(isHTML){e.respondWith(fetch(req).then(function(res){if(res&&res.ok)caches.open(VERSION).then(function(c){c.put(req,res.clone());});return res;}).catch(function(){return caches.match(req).then(function(hit){return hit||caches.match('./index.html');});}));return;}
  e.respondWith(caches.match(req).then(function(hit){return hit||fetch(req).then(function(res){if(res&&res.ok)caches.open(VERSION).then(function(c){c.put(req,res.clone());});return res;});}));
});
